server:
  port: 9000

spring:
  application:
    name: auth_server
  datasource:
    url: jdbc:postgresql://dpg-d58iljn5r7bs738nn93g-a.virginia-postgres.render.com:5432/test_3sju
    username: test_3sju_user
    password: MIfdE90YRdvcG6fGXYsH0U2UqAS4vk7N

  jpa:
    hibernate:
      ddl-auto: update
